#!/usr/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color
#to apply colors we  need to escape  so we add the argument -e  REMINDER TO MYSELF MOSTLY BECAUSE I FORGOT

echo "========="
echo -e "${RED} START/STOP WEB APP SCRIPT ${NC}"
echo "========="

echo -e "${GREEN} Provide SubscriptionID:${NC}"
read -r subscription_id

echo -e "${GREEN} Provide Resource Group:${NC}"
read -r resource_group 

echo -e "${GREEN} Provide Web App name:${NC}"
read -r web_app_name

echo "========="
echo -e "${RED} AUTHENTICATION PROCESS REQUIRED. ${NC} "
az login

az account set --subscription $subscription_id
echo "========="

echo -e "${GREEN} $web_app_name  STATE: ${NC}"
az webapp show --name $web_app_name --resource-group $resource_group --query state
echo "========="

az webapp start --name $web_app_name --resource-group $resource_group

echo -e "${GREEN} ACTION : (start/stop) ${NC}"
read -r action

if [ $action == "start" ];then 
   az webapp start --name $web_app_name --resource-group $resource_group
elif [ $action == "stop" ];then
   az webapp stop --name $web_app_name --resource-group $resource_group
fi
